<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Content\scene1.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Content\scene2.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
        <None Update="Content\scene2.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <!-- Copy all nez effects and textures -->
        <None Update="Content\nez\effects\*;Content\nez\effects\transitions\*;Content\nez\textures\*;Content\nez\textures\textureWipeTransition\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DistortedCore\Nez\Nez.Portable\Nez.MG38.csproj" />
    </ItemGroup>

</Project>
